CREATE DATABASE Equipe_sportive
USE Equipe_sportive;

GO
CREATE TABLE Roles(
Id TINYINT PRIMARY KEY,
Description VARCHAR(20)
);
CREATE TABLE Etat(
Id TINYINT PRIMARY KEY,
Description VARCHAR(20)
);
CREATE TABLE TypeEvenement(
Id TINYINT PRIMARY KEY,
Description VARCHAR(20)
);

CREATE TABLE Utilisateurs(
Id INT IDENTITY PRIMARY KEY,
Nom VARCHAR(30),
Prenom VARCHAR(30),
Email VARCHAR(100),
Adresse VARCHAR(120),
NumTelephone VARCHAR(20),
DateCreation DATETIME2,
DateModification DATETIME2,
EstAthlete BIT,
EstTuteur BIT,
EstEntraineur BIT,
EstAdmin Bit,
Etat TINYINT FOREIGN KEY REFERENCES dbo.Etat (Id)
);

CREATE TABLE Equipes(
Id INT IDENTITY PRIMARY KEY,
Nom VARCHAR(50),
Region VARCHAR(30),
Etat TINYINT FOREIGN KEY REFERENCES dbo.Etat (Id),
DateCreation DATETIME2,
DateModification DATETIME2,
Sport VARCHAR(30),
AssociationSportive VARCHAR(100)
);

CREATE TABLE Evenements(
Id INT IDENTITY PRIMARY KEY,
Description VARCHAR(350) NOT NULL,
Emplacement VARCHAR(200) NOT NULL,
DateDebut DATETIME2,
DateFin DATETIME2,
DateCreation DATETIME2,
DateModification DATETIME2,
Type TINYINT FOREIGN KEY REFERENCES dbo.TypeEvenement (Id),
Etat TINYINT FOREIGN KEY REFERENCES dbo.Etat (Id)
);


CREATE TABLE ConnJoueurEquipe(
Id INT FOREIGN KEY REFERENCES dbo.Utilisateur (Id),
Id INT FOREIGN KEY REFERENCES dbo.Equipe (Id),
Roles TINYINT FOREIGN KEY REFERENCES dbo.Roles (Id),
);

CREATE TABLE ConnEquipeEvenement(
Id INT FOREIGN KEY REFERENCES dbo.Equipe (Id),
Id INT FOREIGN KEY REFERENCES dbo.Evenement (Id)
);